### PR TITLE
Fix "make check" failures (c_api.test, c_thread_api.test)

### PR DESCRIPTION
**Pull request by jforissier**
sqlfs_proc_mkdir() will happily create nested directories. Reflect this
in tests/common.c.

Signed-off-by: Jerome Forissier jerome.forissier@linaro.org

### CODE REVIEW

**Comment by eighthave** [comment]
The question here is whether `sqlfs_proc_mkdir()` should act as plain `mkdir` or `mkdir -p`.  If it follows the POSIX `mkdir()`, then it should not create parent directories, and should instead throw "ENOENT A directory component in pathname does not exist or is a dangling symbolic link."  FUSE methods generally follow POSIX as much as it makes sense.  The FUSE docs say "See mkdir(2) for details", so I assume they follow the behavior of that.  "Testing whether mkdir does not make nested dirs" does pass for me.

**Comment by eighthave** [comment]
I'll try fixing the tests tomorrow.

**Comment by jforissier** [comment]
@eighthave I'm fine with either way (like `mkdir` or like `mkdir -p`). In any case I can confirm that the test fails on my platform (Ubuntu 16.04 x86_64), so, don't you think the bug is actually in libsqlfs and not in the test? (I did not actually check manually if the intermediate directories are indeed created, I can do it if it helps).

**Comment by eighthave** [comment]
Since this is a FUSE-based API, it should retain compatibility.  So that means sticking to the `man 2 open` POSIX approach: if parent dirs do not exist, it should throw `-ENOENT`.  The test passed on my Ubuntu 14.04/amd64, Debian testing/amd64 and the travis-ci Ubuntu 14.04.

**Comment by jforissier** [comment]
To reproduce the issue:
```
./autogen.sh && ./configure --without-fuse && make check
[...]
Testing whether mkdir does not make nested dirs...
lt-c_thread_api: common.c:97: test_mkdir_without_sleep: Assertion `!sqlfs_is_dir(sqlfs, testfilename)' failed.
./c_thread_api.test: line 15:  2135 Aborted                 (core dumped) "$test" "$testsubdir/$testname.db"
FAIL: c_thread_api.test

```

**Comment by eighthave** [comment]
ah, ok, I suppose the tests should also run using `--without-fuse`.  Looks like Andy Tai attempted to fix this here way back when:
https://github.com/guardianproject/libsqlfs/blob/effc5bc58161c465a0babfb85d9b7c622888e527/sqlfs.c#L1700

**Comment by jforissier** [comment]
On Fri, May 6, 2016 at 11:44 AM, Hans-Christoph Steiner <
notifications@github.com> wrote:

> ah, ok, I suppose the tests should also run using --without-fuse.
>

+1


> Looks like Andy Tai attempted to fix this here way back when:
>
> https://github.com/guardianproject/libsqlfs/blob/effc5bc58161c465a0babfb85d9b7c622888e527/sqlfs.c#L1700
>

This doesn't look right.

**Comment by eighthave** [comment]
If you're in that code at the moment, could you fix it? I'm in javaland at the moment...

**Comment by jforissier** [comment]
Updated. I could not understand what issue the code I removed was trying to address, so I hope I did not get this wrong. It seems to me that a call to `sqlfs_proc_access()` is all we need in `check_parent_write()`?
In any case, `make check` runs OK with and without fuse.

**Pull request closed without merging**
